### ISSUE TITLE
Fails to download on Mac

### ISSUE THREAD

**Issue by jamesbirtles** [dkuku/asdf-roc#4]
Thanks for making this!

**Describe the bug**

The download URL 404s when trying to install latest on a Mac

```
Could not download https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-darwin_arm64-latest.tar.gz
```

**Steps to reproduce**

```sh
$ asdf install roc latest
```

**Expected behavior**

It installs roc!

**Screenshots**

<img width="892" alt="CleanShot 2023-11-23 at 20 29 21@2x" src="https://github.com/dkuku/asdf-roc/assets/3743418/6bacc922-9600-4cdc-b6b7-6d1a14ae04ec">

**Additional context**

Looks like the url for Mac (with apple silicon) should be:
```
https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_apple_silicon-latest.tar.gz
```

**Comment by dkuku** [comment]
@jamesbirtles, Thanks for reporting. I should work now, but I did not test it on macos.
```
> asdf plugin remove roc
> asdf plugin add roc https://github.com/dkuku/asdf-roc
```
